module.exports = {
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    PRODUCT_VIEW: "PRODUCT_VIEW",
    PRODUCT_SEARCH: "PRODUCT_SEARCH",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CHECKOUT_INITIATED: "CHECKOUT_INITIATED",
    ORDER_COMPLETED: "ORDER_COMPLETED"
};